language: python
sudo: false
python:
  - "3.6"
  - "3.5"
cache:
  - pip
env:
  global:
    - PIP_INSTALL="pip3 install"
  matrix:
    - PYQT="$PIP_INSTALL pyqt5==5.9"
before_install:
  - $PYQT
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test_environment python=$TRAVIS_PYTHON_VERSION
  - source activate test_environment 
  - conda install pytest pytest-cov coverage sh anaconda-client
  - pip install -r requirements.txt
  - conda list
  - git clone https://github.com/USGS-Astrogeology/PySAT.git
  - cd PySAT
  - python setup.py install
  - cd ..
script:
  - python setup.py clean
  - python setup.py build
  - python setup.py install
# - py.test tests