language: python
cache:
- pip
install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
script:
- bash install_travis.sh
- python setup.py install
deploy:
  provider: pypi
  user: tisaconundrum
  password:
    secure: Qg1BOgRNEzXzkjKddP6I6BXxMes9DwC9w83aZqD94pc+5RVEf/cbumY+0r4y6OPSPEOZ09psWDff/BjpWo7pN1/HQS4FtaD/LPj0cXgONzcNxnacbu9BA4X0rWj3hZoBCV8phxRli3DEBOye00l3EjW7DEzDdVVzMB/XxSexENbqUNuxDdhcfnG1UxZ0+iKa5psDE/cQFTxv3lR1FJyriM/7SA3sSZHB8PSjDP4nLcJCv/U2pyIdhajYAhA9FGkCwaCaYMzEHSUpyx2IQ0GNMcL5LD2QFvn/uelKWkNnOYJqfBpgho/q/nKk2c3ZDpX3U/5jSLLpdeLdwa0yjZIiJe6OsXV2dHM+OxGe5Ib6MftceDEIHmLdozV+KYirN57aKE30k7708sIljyNxsohFaZMFyWiTJDzZqOtoPweY+/rzuRjLTfq4ADFl3GzwgdYVZZpsvaDEaLjEJywIiu0Ss12lbZQBc+a6Kp4dxuqRyQzbDM+M8aPMOs+fic5MdhsbH1uNeL+V/Li2dFmsM33Ed65W0FQzsD0dFQLCT69z510qzhsL68dsLfy6I/BOIRrtMYExfIEnltv/tyQN1HQbaEP/dEVtykcnV1LOMnDIJJ1dDIknjcVqZs60ZIJB3DuPmrgb2majiGhGFBAOIaeKpsXqYiMaWG/gkAnaYtfyTvE=
  distributions: sdist bdist_wheel
  on:
    branch: dev
after_deploy:
- conda env create -n ppsg -f environment.yml
- source activate ppsg
- point_spectra_gui
