name: pysat_point_spectra_gui
dependencies:
  - python=3
 - icu
 - jpeg
 - libpng
 - pyqt
 - qt
 - sip
 - sqlite
 - zlib
 - icc_rt
 - intel-openmp
 - mkl
 - numpy
 - pandas
 - python-dateutil
 - pytz
 - scipy
 - cycler
 - freetype
 - matplotlib
 - tornado 
 - pip:
   - pysat
   - sklearn
   - qtmodern